---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-redis-config
data:
  redis-config: |
    protected-mode no
    # limit memory usage
    maxmemory 6gb
    # evict keys using an LRU policy (least-recently-used)
    # maxmemory-policy allkeys-lru
    # return an error when the memory limit is exceeded
    maxmemory-policy noeviction
    # snapshots on disk every minute
    dir /data/
    appendonly no
    save 60 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
        name: redis-server
    spec:
      # nodeSelector:
      #   node-type: worker
      containers:
      - name: redis-server
        image: redis
        args: ["--requirepass", "SECRET"]
        imagePullPolicy: IfNotPresent
        ports:
          - name: redis-server
            containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: test-redis-config
            items:
            - key: redis-config
              path: redis.conf

---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: default
spec:
  selector:
    app: redis-server
  loadBalancerIP: 0.0.0.0
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer
  